# docker-compose up -d
# docker-compose down -v
# docker exec -it id psql -U admin -d hash_db

version: '3.8'
services:
  postgres:
    extends:
      file: ../components/hashgenerator/deployment/docker-compose.yml
      service: postgres