version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: loh
      POSTGRES_DB: hash_db
    ports:
      - "5432:5432"
    volumes:
    - ../internal/migration:/docker-entrypoint-initdb.d
    restart: unless-stopped